LIBRARY ieee;
USE ieee.std_logic_1164.all;


-- Entity definition based on Slide 22 HINT
ENTITY onebitALU IS
    PORT (
        A        : IN  STD_LOGIC;
        B        : IN  STD_LOGIC;
        less     : IN  STD_LOGIC; -- Input for SLT result (used by LSB)
        carryin  : IN  STD_LOGIC; -- Carry in
        opcode   : IN  STD_LOGIC_VECTOR(3 DOWNTO 0); -- Operation code (ALUctrl)
        result   : OUT STD_LOGIC; -- 1-bit result
        set      : OUT STD_LOGIC; -- Output for SLT determination (used by MSB)
        carryout : OUT STD_LOGIC  -- Carry out
    );
END ENTITY onebitALU;

-- Architecture using only concurrent assignments (as required by Slide 26)
ARCHITECTURE concurrent_logic OF onebitALU IS

    -- Internal signals based on the diagrams (Slides 15-18)
    SIGNAL b_inv      : STD_LOGIC;      -- Inverted B for SUB/SLT/NOR
    SIGNAL adder_cin  : STD_LOGIC;      -- Actual CarryIn to the adder logic
    SIGNAL adder_sum  : STD_LOGIC;      -- Sum output of the adder logic
    SIGNAL adder_cout : STD_LOGIC;      -- Carry output of the adder logic
    SIGNAL and_result : STD_LOGIC;      -- Result of AND operation
    SIGNAL or_result  : STD_LOGIC;      -- Result of OR operation
    SIGNAL nor_result : STD_LOGIC;      -- Result of NOR operation

    -- Control signals derived from opcode
    SIGNAL use_adder  : STD_LOGIC;      -- True for ADD, SUB, SLT
    SIGNAL b_negate   : STD_LOGIC;      -- True for SUB, SLT (part of NOR logic handled differently)

BEGIN

    -- Derive control signals based on opcode (concurrently)
    b_negate <= '1' WHEN opcode = "0110" OR opcode = "0111" ELSE -- SUB or SLT
                '0';

    -- Determine the input to the adder logic for B
    b_inv <= B XOR b_negate; -- Invert B if b_negate is '1'

    -- Determine the carry-in for the adder logic
    -- For SUB/SLT (opcode "0110", "0111"), the effective Cin is '1' (from b_negate)
    -- For ADD (opcode "0010"), the effective Cin is the external 'carryin'
    adder_cin <= carryin OR b_negate;

    -- Full Adder Logic (concurrent calculation)
    adder_sum <= A XOR b_inv XOR adder_cin;
    adder_cout <= (A AND b_inv) OR (A AND adder_cin) OR (b_inv AND adder_cin);

    -- Basic Logic Operations (concurrent calculation)
    and_result <= A AND B;
    or_result  <= A OR B;
    nor_result <= A NOR B; -- Direct NOR implementation

    -- Result multiplexing based on opcode (concurrent assignment with conditional signal assignment)
    result <= and_result WHEN opcode = "0000" ELSE       -- AND
              or_result  WHEN opcode = "0001" ELSE       -- OR
              adder_sum  WHEN opcode = "0010" ELSE       -- ADD
              adder_sum  WHEN opcode = "0110" ELSE       -- SUB
              less       WHEN opcode = "0111" ELSE       -- SLT (Result is determined by 'less' input for LSB, '0' otherwise - handled in 7-bit ALU connections)
              nor_result WHEN opcode = "1100" ELSE       -- NOR
              '0'; -- Default case

    -- CarryOut logic
    -- CarryOut is relevant only for ADD/SUB/SLT which use the adder
    carryout <= adder_cout WHEN opcode = "0010" OR opcode = "0110" OR opcode = "0111" ELSE
                '0'; -- No carry for logical operations

    -- Set logic (for SLT - Slide 17)
    -- The 'set' signal is the sum result of the subtraction performed for SLT
    -- This signal is only meaningful when generated by the MSB.
    set <= adder_sum WHEN opcode = "0111" ELSE -- Set is the sum bit of the MSB during SLT (subtract)
           '0'; -- Not relevant for other operations

END ARCHITECTURE concurrent_logic;